import {
  useEffect,
  useMemo,
  useState
} from "react";

import {
  Link
} from "react-router-dom";

import {
  findMatches
} from "../services/matchingService";

import Button from "../components/ui/Button";
import Card from "../components/ui/Card";
import Badge from "../components/ui/Badge";
import SectionHeader from "../components/ui/SectionHeader";

import {
  createListing
} from "../services/listingService";

import {
  useAuth
} from "../contexts/AuthContext";


function formatCurrency(value) {
  return `₹${Number(
    value || 0
  ).toLocaleString("en-IN")}`;
}


function getRouteValue(
  route,
  valuation
) {
  switch (route) {
    case "parts":
      return Number(
        valuation.partsValue || 0
      );

    case "auction":
      return Math.round(
        (
          Number(
            valuation.auctionMin || 0
          ) +
          Number(
            valuation.auctionMax || 0
          )
        ) / 2
      );

    case "scrap":
      return Number(
        valuation.scrapValue || 0
      );

    case "whole":
    default:
      return Number(
        valuation.wholeValue || 0
      );
  }
}


function buildOtherRoutes(
  valuation,
  recommendedRoute
) {
  const routes = [
    {
      route: "whole",
      name: "Sell Whole",
      value: formatCurrency(
        valuation.wholeValue
      ),
      time: "Fast exit",
      note: "Sell the complete device.",
      href: "/marketplace"
    },

    {
      route: "parts",
      name: "Sell Components",
      value: formatCurrency(
        valuation.partsValue
      ),
      time: "Component recovery",
      note: "Sell useful parts separately.",
      href: "/marketplace"
    },

    {
      route: "auction",
      name: "Auction",
      value:
        `${formatCurrency(
          valuation.auctionMin
        )}–${formatCurrency(
          valuation.auctionMax
        )}`,
      time: "Price discovery",
      note: "Let buyers compete.",
      href: "/auctions"
    },

    {
      route: "scrap",
      name: "Scrap",
      value: formatCurrency(
        valuation.scrapValue
      ),
      time: "Same-day route",
      note: "Recover scrap value.",
      href: "/scrap"
    },

    {
      route: "donate",
      name: "Donate",
      value: "Social impact",
      time: "Non-cash route",
      note: "Prioritize reuse and impact.",
      href: "/dashboard"
    }
  ];

  return routes.filter(
    (route) =>
      route.route !==
      recommendedRoute
  );
}


function formatBuyerType(type) {
  if (!type) {
    return "Buyer";
  }

  return String(type)
    .replaceAll("_", " ")
    .replace(/\b\w/g, (letter) =>
      letter.toUpperCase()
    );
}


export default function SellResultsPage() {
  const [
    evaluation,
    setEvaluation
  ] = useState(null);

  const [
    matchingState,
    setMatchingState
  ] = useState({
    loading: false,
    matches: [],
    error: ""
  });

  const [
    sellContext,
    setSellContext
  ] = useState(null);

  const [
    listingState,
    setListingState
  ] = useState({
    loading: false,
    message: "",
    error: ""
  });

  const [createdListingId, setCreatedListingId] = useState(null);

  const {
    isAuthenticated,
    user
  } = useAuth();




  /*
   * Load the AI evaluation + sell context
   * generated by SellPage.
   */
  useEffect(() => {
    const stored =
      sessionStorage.getItem(
        "revalue_ai_eval"
      );

    if (stored) {
      try {
        setEvaluation(
          JSON.parse(stored)
        );
      } catch {
        setEvaluation(null);
      }
    }

    const context =
      sessionStorage.getItem(
        "revalue_sell_context"
      );

    if (context) {
      try {
        setSellContext(
          JSON.parse(context)
        );
      } catch {
        setSellContext(null);
      }
    }
  }, []);


  const recommendation =
    useMemo(
      () =>
        evaluation?.recommendation ||
        null,
      [evaluation]
    );


  const valuation =
    useMemo(
      () =>
        evaluation?.valuation ||
        {},
      [evaluation]
    );


  const detectedItem =
    useMemo(
      () =>
        evaluation?.detectedItem ||
        {},
      [evaluation]
    );


  const condition =
    useMemo(
      () =>
        evaluation?.condition ||
        {},
      [evaluation]
    );


  const marketSignals =
    useMemo(
      () =>
        evaluation?.marketSignals ||
        {},
      [evaluation]
    );


  const components =
    useMemo(
      () =>
        evaluation?.components ||
        [],
      [evaluation]
    );


  const recommendedValue =
    useMemo(
      () =>
        getRouteValue(
          recommendation?.route,
          valuation
        ),
      [
        recommendation?.route,
        valuation
      ]
    );


  /*
   * -------------------------------------------------
   * TASK E — MATCHING ENGINE INPUT
   * -------------------------------------------------
   *
   * No fake listing is created here.
   *
   * We construct the input using the real
   * output from the AI / Task C evaluation.
   */
  const matchingInput =
    useMemo(() => {
      if (!evaluation) {
        return null;
      }

      const category =
        evaluation
          ?.categoryDecision
          ?.finalCategory ||
        detectedItem
          ?.category
          ?.toLowerCase() ||
        sellContext?.category ||
        null;

      if (!category) {
        return null;
      }

      return {
        category,

        location:
          marketSignals.location ||
          sellContext?.location ||
          "Delhi",

        /*
         * Consumer Sell flow represents
         * one item.
         *
         * Business/bulk flows can later
         * supply their actual quantity.
         */
        quantity: 1,

        condition:
          condition.label ||
          "fair",

        /*
         * Matching uses the value of the
         * recommended route where possible.
         */
        price:
          recommendedValue ||
          valuation.wholeValue ||
          0,

        limit: 5
      };
    }, [
      evaluation,
      detectedItem.category,
      sellContext?.category,
      sellContext?.location,
      marketSignals.location,
      condition.label,
      recommendedValue,
      valuation.wholeValue
    ]);


  /*
   * -------------------------------------------------
   * TASK E — CALL MATCHING ENGINE
   * -------------------------------------------------
   *
   * Results page loads:
   *
   * AI result
   *      ↓
   * matchingInput
   *      ↓
   * POST /api/matching/find
   *      ↓
   * ranked counterparties
   */
  useEffect(() => {
    if (!matchingInput) {
      return undefined;
    }

    let cancelled = false;

    async function loadMatches() {
      setMatchingState({
        loading: true,
        matches: [],
        error: ""
      });

      try {
        const result =
          await findMatches(
            matchingInput
          );

        if (cancelled) {
          return;
        }

        setMatchingState({
          loading: false,
          matches:
            Array.isArray(
              result?.matches
            )
              ? result.matches
              : [],
          error: ""
        });
      } catch (error) {
        if (cancelled) {
          return;
        }

        console.error(
          "Matching engine failed:",
          error
        );

        setMatchingState({
          loading: false,
          matches: [],
          error:
            error.message ||
            "Unable to find matching buyers."
        });
      }
    }

    loadMatches();

    return () => {
      cancelled = true;
    };
  }, [matchingInput]);


  /*
   * Useful during hackathon testing.
   *
   * Open F12 -> Console and verify that
   * real ranked matches are returned.
   */
  useEffect(() => {
    if (
      matchingState.matches.length >
      0
    ) {
      console.log(
        "MATCHING ENGINE:",
        matchingState.matches
      );
    }
  }, [matchingState.matches]);


  const otherRoutes =
    useMemo(
      () =>
        buildOtherRoutes(
          valuation,
          recommendation?.route
        ),
      [
        valuation,
        recommendation?.route
      ]
    );


  async function handleCreateListing() {
    if (!isAuthenticated) {
      setListingState({
        loading: false,
        message: "",
        error:
          "Please sign in before publishing a listing."
      });

      return;
    }

    const route =
      recommendation?.route ||
      "whole";

    const saleType =
      route === "auction"
        ? "auction"

        : route === "parts"
        ? "parts"

        : route === "scrap"
        ? "scrap"

        : route === "donate"
        ? "donation"

        : "fixed";

    setListingState({
      loading: true,
      message: "",
      error: ""
    });

    try {
      const payload = {
        category:
          (
            detectedItem.category ||
            sellContext?.category ||
            "electronics"
          ).toLowerCase(),

        subcategory:
          route === "parts"
            ? "component"
            : (
                detectedItem.category ||
                sellContext?.category ||
                "device"
              ).toLowerCase(),

        brand:
          detectedItem.brand ||
          "Punarchakra",

        model:
          detectedItem.model ||
          "Device",

        condition:
          condition.label ||
          "Good",

        description:
          recommendation?.reason ||
          "Listed from the Punarchakra AI evaluation flow.",

        images:
          sellContext
            ?.images
            ?.length
            ? sellContext.images
            : [
                "https://via.placeholder.com/400?text=Punarchakra+Listing"
              ],

        price:
          recommendedValue,

        location:
          marketSignals.location ||
          sellContext?.location ||
          "Delhi",

        sale_type:
          saleType,

        status:
          "active"
      };

      const created = await createListing(
        payload
      );

      if (created?.id) {
        setCreatedListingId(created.id);
      }

      setListingState({
        loading: false,

        message:
          `Listing published for ${
            user?.name ||
            "you"
          }.`,

        error: ""
      });
    } catch (error) {
      setListingState({
        loading: false,
        message: "",

        error:
          error.message ||
          "Unable to create the listing right now."
      });
    }
  }


  if (!evaluation) {
    return (
      <main className="container section">
        <Card>
          <SectionHeader
            eyebrow="No evaluation"
            title="No AI result found"
            description="Run the Sell Item evaluation first."
          />

          <Button
            as={Link}
            to="/sell"
            variant="primary"
          >
            Evaluate an item
          </Button>
        </Card>
      </main>
    );
  }


  const recoveryDifference =
    Number(
      valuation.partsValue || 0
    ) -
    Number(
      valuation.wholeValue || 0
    );


  return (
    <main className="container section sell-results-page">

      <div className="page-intro">

        <div className="eyebrow">
          AI valuation complete
        </div>

        <h1>
          Best route for your device
        </h1>

        <p>
          {detectedItem.brand ||
            "Device"}{" "}

          {detectedItem.model ||
            ""}

          {" • "}

          {condition.label ||
            "Condition"}
        </p>

        <p className="page-intro__description">
          Punarchakra uses AI to compare
          device condition, resale
          demand and recovery routes.
        </p>

      </div>


      <section className="recommendation-panel">

        <div className="recommendation-panel__tag">

          <Badge>
            BEST ROUTE
          </Badge>

          <span className="recommendation-panel__subtag">

            {recommendation?.label ||
              "Recommended route"}

          </span>

        </div>


        <div className="recommendation-panel__heading">

          <h2>
            {recommendation?.label ||
              "Recommended route"}
          </h2>

          <div className="recommendation-panel__pill">
            AI recommendation
          </div>

        </div>


        <p className="recommendation-panel__subtitle">

          {recommendation?.reason ||
            "Punarchakra selected the strongest recovery route."}

        </p>


        <div className="recommendation-panel__metrics grid grid-3">

          <div className="recommendation-panel__metric">

            <span className="eyebrow">
              Estimated recovery
            </span>

            <div className="metric">

              {formatCurrency(
                recommendedValue
              )}

            </div>

          </div>


          <div className="recommendation-panel__metric">

            <span className="eyebrow">
              AI confidence
            </span>

            <div className="metric">

              {evaluation?.confidence
                ? `${evaluation.confidence}%`
                : "—"}

            </div>

          </div>


          <div className="recommendation-panel__metric">

            <span className="eyebrow">
              Market demand
            </span>

            <div className="metric">

              {marketSignals.demand
                ? String(
                    marketSignals.demand
                  ).toUpperCase()
                : "—"}

            </div>

          </div>

        </div>


        <p className="recommendation-panel__copy">

          {recommendation?.reason ||
            "The decision engine compares resale, parts, auction and scrap recovery."}

        </p>


        <div className="recommendation-panel__compare">

          <span className="eyebrow">
            Recommended route vs whole sale
          </span>

          <strong>

            {recoveryDifference > 0
              ? `${formatCurrency(
                  recoveryDifference
                )} more recovered`

              : "Strongest route for current condition"}

          </strong>

        </div>


        <div className="wizard-actions">

          <Button
            as={Link}
            variant="secondary"
            to="/marketplace"
            className="recommendation-panel__cta"
          >
            Browse marketplace
          </Button>


          {createdListingId ? (
            <Button
              as={Link}
              variant="primary"
              to={`/agent/${createdListingId}`}
            >
              Start Autonomous Resolution →
            </Button>
          ) : (
            <Button
              variant="primary"
              onClick={
                handleCreateListing
              }
              disabled={
                listingState.loading
              }
            >

              {listingState.loading
                ? "Publishing..."
                : "Publish listing"}

            </Button>
          )}

        </div>


        {listingState.message ? (
          <p className="page-intro__description">
            {
              listingState.message
            }
          </p>
        ) : null}


        {listingState.error ? (
          <p className="page-intro__description">
            {
              listingState.error
            }
          </p>
        ) : null}

      </section>


      <section className="section decision-summary">

        <div className="decision-summary__cards grid grid-3">

          <Card className="highlight-card">

            <div className="eyebrow">
              Whole device value
            </div>

            <div className="metric">

              {formatCurrency(
                valuation.wholeValue
              )}

            </div>

          </Card>


          <Card className="highlight-card highlight-card--positive">

            <div className="eyebrow">
              Parts value
            </div>

            <div className="metric">

              {formatCurrency(
                valuation.partsValue
              )}

            </div>

          </Card>


          <Card className="highlight-card">

            <div className="eyebrow">
              Scrap value
            </div>

            <div className="metric">

              {formatCurrency(
                valuation.scrapValue
              )}

            </div>

          </Card>

        </div>

      </section>


      <section className="section decision-detail grid grid-2">

        <Card className="breakdown-card">

          <div className="breakdown-card__header">

            <h3>
              Value breakdown
            </h3>

            <span className="eyebrow">
              Component recovery
            </span>

          </div>


          <div className="value-breakdown">

            {components.length > 0
              ? components.map(
                  (component) => (

                    <div
                      key={
                        component.name
                      }
                    >

                      <span>
                        {
                          component.name
                        }
                      </span>

                      <strong>

                        {formatCurrency(
                          component.estimatedValue
                        )}

                      </strong>

                    </div>

                  )
                )

              : (

                <div>

                  <span>
                    Estimated components
                  </span>

                  <strong>

                    {formatCurrency(
                      valuation.partsValue
                    )}

                  </strong>

                </div>

              )}

          </div>


          <div className="value-total">

            <span>
              Total
            </span>

            <strong>

              {formatCurrency(
                valuation.partsValue
              )}

            </strong>

          </div>

        </Card>


        <Card className="recommendation-detail-card">

          <SectionHeader
            eyebrow="Decision engine"
            title="Why does Punarchakra recommend this?"
            description={
              recommendation?.reason ||
              "The route is selected using condition, demand and recovery value."
            }
          />


          <div className="recommendation-detail-card__explanation">

            <p>

              {recommendation?.reason ||
                "The decision engine compares the available recovery routes."}

            </p>

          </div>


          <details className="explain-details">

            <summary>
              See the full reasoning
            </summary>


            <p>
              Whole-device value:{" "}
              <strong>
                {formatCurrency(
                  valuation.wholeValue
                )}
              </strong>
            </p>


            <p>
              Parts value:{" "}
              <strong>
                {formatCurrency(
                  valuation.partsValue
                )}
              </strong>
            </p>


            <p>
              Auction range:{" "}
              <strong>

                {formatCurrency(
                  valuation.auctionMin
                )}

                {" – "}

                {formatCurrency(
                  valuation.auctionMax
                )}

              </strong>
            </p>


            <p>
              Scrap value:{" "}
              <strong>

                {formatCurrency(
                  valuation.scrapValue
                )}

              </strong>
            </p>


            <p>
              Demand signal:{" "}
              <strong>

                {marketSignals.demand ||
                  "Not available"}

              </strong>
            </p>

          </details>

        </Card>

      </section>


      {/*
       * -------------------------------------------------
       * TASK E — MATCHING ENGINE UI
       * -------------------------------------------------
       *
       * Deliberately small/subtle.
       *
       * Uses existing Card/grid styling so it does not
       * look like a large late frontend redesign.
       */}
      <section className="section">

        <SectionHeader
          eyebrow="BUYER MATCHES"
          title="Interested buyers"
          description="Best counterparties for this item based on price, demand, distance, rating and quantity."
        />


        {matchingState.loading ? (
          <Card>
            <p>
              Finding the best buyers for this item...
            </p>
          </Card>
        ) : null}


        {!matchingState.loading &&
        matchingState.error ? (
          <Card>
            <p>
              Matching is temporarily unavailable.
            </p>
          </Card>
        ) : null}


        {!matchingState.loading &&
        !matchingState.error &&
        matchingState.matches.length ===
          0 ? (
          <Card>
            <p>
              No strong buyer matches found for this item yet.
            </p>
          </Card>
        ) : null}


        {matchingState.matches.length >
        0 ? (
          <div className="grid grid-3">

            {matchingState.matches
              .slice(0, 3)
              .map((match) => (

                <Card
                  key={match.id}
                  className="route-card"
                >

                  <div className="route-card__top">

                    <div>

                      <div className="eyebrow">
                        #{match.rank} MATCH
                      </div>

                      <strong>
                        {match.name}
                      </strong>

                      <p>
                        {formatBuyerType(
                          match.type
                        )}
                      </p>

                    </div>


                    <span className="route-card__value">
                      {Math.round(
                        Number(
                          match.matchScore ||
                          0
                        )
                      )}
                      %
                    </span>

                  </div>


                  <div className="route-card__meta">

                    <span>
                      {match.location}

                      {Number.isFinite(
                        Number(
                          match.distanceKm
                        )
                      )
                        ? ` • ${match.distanceKm} km`
                        : ""}
                    </span>

                    <span>
                      ★ {match.rating}
                    </span>

                  </div>


                  {Array.isArray(
                    match.reasons
                  ) &&
                  match.reasons.length >
                    0 ? (
                    <p
                      style={{
                        marginTop: 12
                      }}
                    >
                      {
                        match.reasons[
                          0
                        ]
                      }
                    </p>
                  ) : null}

                </Card>

              ))}

          </div>
        ) : null}

      </section>


      <section className="section">

        <SectionHeader
          eyebrow="OTHER ROUTES"
          title="Other routes"
          description="Compare alternate routes calculated from this evaluation."
        />


        <div className="route-grid">

          {otherRoutes.map(
            (route) => (

              <Card
                key={
                  route.route
                }
                className="route-card"
              >

                <div className="route-card__top">

                  <div>

                    <strong>
                      {
                        route.name
                      }
                    </strong>

                    <p>
                      {
                        route.note
                      }
                    </p>

                  </div>


                  <span className="route-card__value">

                    {
                      route.value
                    }

                  </span>

                </div>


                <div className="route-card__meta">

                  <span>
                    {
                      route.time
                    }
                  </span>


                  <Button
                    as={Link}
                    variant="secondary"
                    to={
                      route.href
                    }
                  >

                    {route.route ===
                    "donate"
                      ? "Learn more"
                      : "Explore route"}

                  </Button>

                </div>

              </Card>

            )
          )}

        </div>

      </section>

    </main>
  );
}